runtime: python39

entrypoint: gunicorn -b :$PORT app:app

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
  # Add any environment variables your app requires
  FLASK_ENV: production
