runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  # Add any environment variables your app requires
  FLASK_ENV: production

automatic_scaling:
  target_cpu_utilization: 0.65
